--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: book; Type: TABLE; Schema: public; Owner: pruebas
--

CREATE TABLE public.book (
    id integer NOT NULL,
    author character varying(255),
    category character varying(255),
    genre character varying(255),
    rating double precision NOT NULL,
    title character varying(255),
    user_id integer
);


ALTER TABLE public.book OWNER TO pruebas;

--
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: pruebas
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: pruebas
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_name character varying(100) NOT NULL,
    user_email character varying(100) NOT NULL,
    user_pssword character varying(255) NOT NULL,
    date_registry timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.users OWNER TO pruebas;

--
-- Name: books_x_users; Type: VIEW; Schema: public; Owner: pruebas
--

CREATE VIEW public.books_x_users AS
 SELECT u.user_id,
    u.user_name,
    b.id,
    b.title
   FROM (public.users u
     JOIN public.book b ON ((u.user_id = b.user_id)));


ALTER VIEW public.books_x_users OWNER TO pruebas;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: pruebas
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_user_id_seq OWNER TO pruebas;

--
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: pruebas
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: pruebas
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: pruebas
--

COPY public.book (id, author, category, genre, rating, title, user_id) FROM stdin;
1	Fiódor Dostoyevski	Ficcion literaria	Ficcion literaria	5	Noches blancas	\N
2	Fiódor Dostoyevski	Ficcion literaria	Ficcion literaria	5	Noches blancas	\N
7	author	category	genre	0	title	\N
8	author	category	genre	0	title	\N
9	Miguel de Cervantes	Novela	Ficción	4.5	El Quijote	\N
10	Fiódor Dostoyevski	Realismo	Realismo	5	Los hermanos Karamasov	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: pruebas
--

COPY public.users (user_id, user_name, user_email, user_pssword, date_registry) FROM stdin;
1	Jhon Jardi Diaz Lora	jhon.diaz@linktic.com	Pruebas123	2025-02-11 13:26:41.505531
\.


--
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pruebas
--

SELECT pg_catalog.setval('public.book_id_seq', 10, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: pruebas
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);


--
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: pruebas
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: pruebas
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: users users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: pruebas
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_user_email_key UNIQUE (user_email);


--
-- Name: book fk_user; Type: FK CONSTRAINT; Schema: public; Owner: pruebas
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--

