
spring:
  application:
    name: msvc-book
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/bd_library
    username: postgres
    password: pruebas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: msvc-eureka
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka