server:
  port: 8070
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: books
          uri: http://msvc-book:8090
          predicates:
            - Path=/api/library/**
        - id: export
          uri: http://msvc-export:9090
          predicates:
            - Path=/api/export/**
#eureka:
#  client:
#    register-with-eureka: false
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka