server:
  port: 8088

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: books
          uri: lb://msvc-book
          predicates:
            - Path=/api/library/**
        - id: export
          uri: lb://msvc-export
          predicates:
            - Path=/api/export**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG